# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-29 13:44
from __future__ import unicode_literals

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=app.models.upload_image_path),
        ),
    ]
