# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-29 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_slider'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='description',
            field=models.TextField(default=123),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slider',
            name='title',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slider',
            name='title_2',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
