# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-30 09:12
from __future__ import unicode_literals

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20181130_0911'),
    ]

    operations = [
        migrations.AddField(
            model_name='social',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=app.models.upload_image_path),
        ),
    ]
