# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-30 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='pages',
            field=models.ManyToManyField(to='app.Page'),
        ),
    ]
