# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-12-01 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20181130_1033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='app',
            name='pages',
        ),
        migrations.AddField(
            model_name='app',
            name='pages',
            field=models.ManyToManyField(to='app.Page'),
        ),
    ]
