# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-12-02 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20181202_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='dscription',
            field=models.TextField(),
        ),
    ]
