# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-12-02 13:56
from __future__ import unicode_literals

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20181202_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_detail',
            field=models.ImageField(blank=True, null=True, upload_to=products.models.upload_image_path),
        ),
    ]
