# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-12-02 14:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_image_detail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image_detail',
            new_name='imgdetail',
        ),
    ]
