# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-12-04 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_featured'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='dscription',
            new_name='description',
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='abc'),
        ),
    ]
